TYPO3:
  Neos:
    userInterface:
      editPreviewModes:
        ttreePluginSeoAccessibility:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'ttreePluginSeoAccessibility'
          title: 'Accessibility'
          position: 80
        ttreePluginSeoGoogle:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'ttreePluginSeoGoogle'
          title: 'Google Search'
          position: 100