TYPO3:
  Neos:
    userInterface:
      editPreviewModes:
        ttreePluginSeoGoogle:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'ttreePluginSeoGoogle'
          title: 'Google Search'
          position: 100